//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by xsd, Version=4.8.3928.0.
// 
namespace RegiX.Class.Nacid.RdpzsdRegisterEntriesSearch {
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://egov.bg/RegiX/NACID/Rdpzsd/RdpzsdRegisterEntriesResponse")]
    [System.Xml.Serialization.XmlRootAttribute("RdpzsdRegisterEntriesResponse", Namespace="http://egov.bg/RegiX/NACID/Rdpzsd/RdpzsdRegisterEntriesResponse", IsNullable=false)]
    public partial class RdpzsdRegisterEntriesResponseType {
        
        private RdpzsdRegisterEntryType[] rdpzsdRegisterEntryField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("RdpzsdRegisterEntry")]
        public RdpzsdRegisterEntryType[] RdpzsdRegisterEntry {
            get {
                return this.rdpzsdRegisterEntryField;
            }
            set {
                this.rdpzsdRegisterEntryField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://egov.bg/RegiX/NACID/Rdpzsd/RdpzsdRegisterEntriesResponse")]
    public partial class RdpzsdRegisterEntryType {
        
        private string fullNameField;
        
        private string uanField;
        
        private string uinField;
        
        private string idNumberField;
        
        private string emailField;
        
        private SpecialityInfoType[] specialityInfoField;
        
        private DoctoralInfoType[] doctoralInfoField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string FullName {
            get {
                return this.fullNameField;
            }
            set {
                this.fullNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Uan {
            get {
                return this.uanField;
            }
            set {
                this.uanField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Uin {
            get {
                return this.uinField;
            }
            set {
                this.uinField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string IdNumber {
            get {
                return this.idNumberField;
            }
            set {
                this.idNumberField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Email {
            get {
                return this.emailField;
            }
            set {
                this.emailField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("SpecialityInfo")]
        public SpecialityInfoType[] SpecialityInfo {
            get {
                return this.specialityInfoField;
            }
            set {
                this.specialityInfoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("DoctoralInfo")]
        public DoctoralInfoType[] DoctoralInfo {
            get {
                return this.doctoralInfoField;
            }
            set {
                this.doctoralInfoField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://egov.bg/RegiX/NACID/Rdpzsd/RdpzsdRegisterEntriesResponse")]
    public partial class SpecialityInfoType {
        
        private string institutionField;
        
        private string admissionReasonField;
        
        private string specialityField;
        
        private string municipalityField;
        
        private string educationFormField;
        
        private string educationalQualificationField;
        
        private string studentStatusField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Institution {
            get {
                return this.institutionField;
            }
            set {
                this.institutionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string AdmissionReason {
            get {
                return this.admissionReasonField;
            }
            set {
                this.admissionReasonField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Speciality {
            get {
                return this.specialityField;
            }
            set {
                this.specialityField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Municipality {
            get {
                return this.municipalityField;
            }
            set {
                this.municipalityField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string EducationForm {
            get {
                return this.educationFormField;
            }
            set {
                this.educationFormField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string EducationalQualification {
            get {
                return this.educationalQualificationField;
            }
            set {
                this.educationalQualificationField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string StudentStatus {
            get {
                return this.studentStatusField;
            }
            set {
                this.studentStatusField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://egov.bg/RegiX/NACID/Rdpzsd/RdpzsdRegisterEntriesResponse")]
    public partial class DoctoralInfoType {
        
        private string institutionField;
        
        private string admissionReasonField;
        
        private string specialityField;
        
        private string municipalityField;
        
        private string educationFormField;
        
        private string educationalQualificationField;
        
        private string startDateField;
        
        private string durationField;
        
        private string studentStatusField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Institution {
            get {
                return this.institutionField;
            }
            set {
                this.institutionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string AdmissionReason {
            get {
                return this.admissionReasonField;
            }
            set {
                this.admissionReasonField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Speciality {
            get {
                return this.specialityField;
            }
            set {
                this.specialityField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Municipality {
            get {
                return this.municipalityField;
            }
            set {
                this.municipalityField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string EducationForm {
            get {
                return this.educationFormField;
            }
            set {
                this.educationFormField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string EducationalQualification {
            get {
                return this.educationalQualificationField;
            }
            set {
                this.educationalQualificationField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string StartDate {
            get {
                return this.startDateField;
            }
            set {
                this.startDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Duration {
            get {
                return this.durationField;
            }
            set {
                this.durationField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string StudentStatus {
            get {
                return this.studentStatusField;
            }
            set {
                this.studentStatusField = value;
            }
        }
    }
}
