//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by xsd, Version=4.8.3928.0.
// 
namespace RegiX.Class.AVTR.PersonInCompaniesSearch {
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://egov.bg/RegiX/AV/TR")]
    [System.Xml.Serialization.XmlRootAttribute("TestStatusType", Namespace="http://egov.bg/RegiX/AV/TR", IsNullable=false)]
    public enum StatusType {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("Нова партида")]
        Новапартида,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("Пререгистрирана партида")]
        Пререгистриранапартида,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("Нова закрита партида")]
        Новазакритапартида,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("Пререгистрирана закрита партида")]
        Пререгистрираназакритапартида,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://egov.bg/RegiX/AV/TR/SearchParticipationInCompaniesResponse")]
    [System.Xml.Serialization.XmlRootAttribute("SearchParticipationInCompaniesResponse", Namespace="http://egov.bg/RegiX/AV/TR/SearchParticipationInCompaniesResponse", IsNullable=false)]
    public partial class SearchParticipationInCompaniesResponseType {
        
        private bool isFoundField;
        
        private bool isFoundFieldSpecified;
        
        private SubjectType personInformationField;
        
        private CompanyParticipationTypeCompany[] companyParticipationField;
        
        private System.DateTime dataValidForDateField;
        
        private bool dataValidForDateFieldSpecified;
        
        /// <remarks/>
        public bool IsFound {
            get {
                return this.isFoundField;
            }
            set {
                this.isFoundField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool IsFoundSpecified {
            get {
                return this.isFoundFieldSpecified;
            }
            set {
                this.isFoundFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public SubjectType PersonInformation {
            get {
                return this.personInformationField;
            }
            set {
                this.personInformationField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("Company", Namespace="http://egov.bg/RegiX/AV/TR", IsNullable=false)]
        public CompanyParticipationTypeCompany[] CompanyParticipation {
            get {
                return this.companyParticipationField;
            }
            set {
                this.companyParticipationField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime DataValidForDate {
            get {
                return this.dataValidForDateField;
            }
            set {
                this.dataValidForDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool DataValidForDateSpecified {
            get {
                return this.dataValidForDateFieldSpecified;
            }
            set {
                this.dataValidForDateFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://egov.bg/RegiX/AV/TR")]
    public partial class SubjectType {
        
        private string indentField;
        
        private string nameField;
        
        private IndentTypeType indentTypeField;
        
        private bool indentTypeFieldSpecified;
        
        /// <remarks/>
        public string Indent {
            get {
                return this.indentField;
            }
            set {
                this.indentField = value;
            }
        }
        
        /// <remarks/>
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        public IndentTypeType IndentType {
            get {
                return this.indentTypeField;
            }
            set {
                this.indentTypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool IndentTypeSpecified {
            get {
                return this.indentTypeFieldSpecified;
            }
            set {
                this.indentTypeFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://egov.bg/RegiX/AV/TR")]
    public enum IndentTypeType {
        
        /// <remarks/>
        EGN,
        
        /// <remarks/>
        UIC,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://egov.bg/RegiX/AV/TR")]
    public partial class LegalFormType {
        
        private string legalFormAbbrField;
        
        private string legalFormNameField;
        
        /// <remarks/>
        public string LegalFormAbbr {
            get {
                return this.legalFormAbbrField;
            }
            set {
                this.legalFormAbbrField = value;
            }
        }
        
        /// <remarks/>
        public string LegalFormName {
            get {
                return this.legalFormNameField;
            }
            set {
                this.legalFormNameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://egov.bg/RegiX/AV/TR")]
    public partial class CompanyParticipationTypeCompany {
        
        private string eIKField;
        
        private string companyNameField;
        
        private LegalFormType legalFormField;
        
        private string[] fieldsField;
        
        /// <remarks/>
        public string EIK {
            get {
                return this.eIKField;
            }
            set {
                this.eIKField = value;
            }
        }
        
        /// <remarks/>
        public string CompanyName {
            get {
                return this.companyNameField;
            }
            set {
                this.companyNameField = value;
            }
        }
        
        /// <remarks/>
        public LegalFormType LegalForm {
            get {
                return this.legalFormField;
            }
            set {
                this.legalFormField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("Field", IsNullable=false)]
        public string[] Fields {
            get {
                return this.fieldsField;
            }
            set {
                this.fieldsField = value;
            }
        }
    }
}
