//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by xsd, Version=4.8.3928.0.
// 
namespace RegiX.Class.NapooStudentDocuments.GetStudentDocument.Request {
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://egov.bg/RegiX/NAPOO/DocumentsByStudentRequest")]
    [System.Xml.Serialization.XmlRootAttribute("StudentDocumentRequest", Namespace="http://egov.bg/RegiX/NAPOO/DocumentsByStudentRequest", IsNullable=false)]
    public partial class StudentDocumentRequestType {
        
        private string studentIdentifierField;
        
        private string documentRegistrationNumberField;
        
        /// <remarks/>
        public string StudentIdentifier {
            get {
                return this.studentIdentifierField;
            }
            set {
                this.studentIdentifierField = value;
            }
        }
        
        /// <remarks/>
        public string DocumentRegistrationNumber {
            get {
                return this.documentRegistrationNumberField;
            }
            set {
                this.documentRegistrationNumberField = value;
            }
        }
    }
}
