//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by xsd, Version=4.8.3928.0.
// 
namespace RegiX.Class.AVTR.GetActualStateV2 {
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://egov.bg/RegiX/AV/TR/ActualStateResponseV2")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://egov.bg/RegiX/AV/TR/ActualStateResponseV2", IsNullable=false)]
    public partial class ActualStateResponseV2 {
        
        private DeedType deedField;
        
        private System.DateTime dataValidForDateField;
        
        private bool dataValidForDateFieldSpecified;
        
        /// <remarks/>
        public DeedType Deed {
            get {
                return this.deedField;
            }
            set {
                this.deedField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime DataValidForDate {
            get {
                return this.dataValidForDateField;
            }
            set {
                this.dataValidForDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool DataValidForDateSpecified {
            get {
                return this.dataValidForDateFieldSpecified;
            }
            set {
                this.dataValidForDateFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://egov.bg/RegiX/AV/TR/ActualStateResponseV2")]
    public partial class DeedType {
        
        private DeedStatusType deedStatusField;
        
        private string companyNameField;
        
        private string gUIDField;
        
        private string uICField;
        
        private LegalFormType legalFormField;
        
        private string caseNoField;
        
        private string caseYearField;
        
        private string courtNoField;
        
        private LiquidationOrInsolvency liquidationOrInsolvencyField;
        
        private bool liquidationOrInsolvencyFieldSpecified;
        
        private Record[] recordsField;
        
        /// <remarks/>
        public DeedStatusType DeedStatus {
            get {
                return this.deedStatusField;
            }
            set {
                this.deedStatusField = value;
            }
        }
        
        /// <remarks/>
        public string CompanyName {
            get {
                return this.companyNameField;
            }
            set {
                this.companyNameField = value;
            }
        }
        
        /// <remarks/>
        public string GUID {
            get {
                return this.gUIDField;
            }
            set {
                this.gUIDField = value;
            }
        }
        
        /// <remarks/>
        public string UIC {
            get {
                return this.uICField;
            }
            set {
                this.uICField = value;
            }
        }
        
        /// <remarks/>
        public LegalFormType LegalForm {
            get {
                return this.legalFormField;
            }
            set {
                this.legalFormField = value;
            }
        }
        
        /// <remarks/>
        public string CaseNo {
            get {
                return this.caseNoField;
            }
            set {
                this.caseNoField = value;
            }
        }
        
        /// <remarks/>
        public string CaseYear {
            get {
                return this.caseYearField;
            }
            set {
                this.caseYearField = value;
            }
        }
        
        /// <remarks/>
        public string CourtNo {
            get {
                return this.courtNoField;
            }
            set {
                this.courtNoField = value;
            }
        }
        
        /// <remarks/>
        public LiquidationOrInsolvency LiquidationOrInsolvency {
            get {
                return this.liquidationOrInsolvencyField;
            }
            set {
                this.liquidationOrInsolvencyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool LiquidationOrInsolvencySpecified {
            get {
                return this.liquidationOrInsolvencyFieldSpecified;
            }
            set {
                this.liquidationOrInsolvencyFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public Record[] Records {
            get {
                return this.recordsField;
            }
            set {
                this.recordsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://egov.bg/RegiX/AV/TR/ActualStateResponseV2")]
    public enum DeedStatusType {
        
        /// <remarks/>
        N,
        
        /// <remarks/>
        E,
        
        /// <remarks/>
        C,
        
        /// <remarks/>
        L,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://egov.bg/RegiX/AV/TR/ActualStateResponseV2")]
    public enum LegalFormType {
        
        /// <remarks/>
        ET,
        
        /// <remarks/>
        SD,
        
        /// <remarks/>
        KD,
        
        /// <remarks/>
        OOD,
        
        /// <remarks/>
        EOOD,
        
        /// <remarks/>
        AD,
        
        /// <remarks/>
        EAD,
        
        /// <remarks/>
        IAD,
        
        /// <remarks/>
        IEAD,
        
        /// <remarks/>
        KDA,
        
        /// <remarks/>
        K,
        
        /// <remarks/>
        KCHT,
        
        /// <remarks/>
        TPPD,
        
        /// <remarks/>
        TPPO,
        
        /// <remarks/>
        TPP,
        
        /// <remarks/>
        EUIE,
        
        /// <remarks/>
        DEUIE,
        
        /// <remarks/>
        ED,
        
        /// <remarks/>
        EKD,
        
        /// <remarks/>
        LEKD,
        
        /// <remarks/>
        CHD,
        
        /// <remarks/>
        CHDF,
        
        /// <remarks/>
        CHDU,
        
        /// <remarks/>
        SDR,
        
        /// <remarks/>
        FOND,
        
        /// <remarks/>
        KLCHULNC,
        
        /// <remarks/>
        NCH,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("-1")]
        Item1,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://egov.bg/RegiX/AV/TR/ActualStateResponseV2")]
    public enum LiquidationOrInsolvency {
        
        /// <remarks/>
        Liquidation,
        
        /// <remarks/>
        Insolvency,
        
        /// <remarks/>
        InsolvencySecIns,
        
        /// <remarks/>
        InsolvencyThirdIns,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://egov.bg/RegiX/AV/TR/ActualStateResponseV2")]
    public partial class Record {
        
        private object recordDataField;
        
        private int recordIdField;
        
        private int incomingIdField;
        
        private string fieldIdentField;
        
        private Field mainFieldField;
        
        private string fieldEntryNumberField;
        
        private System.DateTime fieldActionDateField;
        
        /// <remarks/>
        public object RecordData {
            get {
                return this.recordDataField;
            }
            set {
                this.recordDataField = value;
            }
        }
        
        /// <remarks/>
        public int RecordId {
            get {
                return this.recordIdField;
            }
            set {
                this.recordIdField = value;
            }
        }
        
        /// <remarks/>
        public int IncomingId {
            get {
                return this.incomingIdField;
            }
            set {
                this.incomingIdField = value;
            }
        }
        
        /// <remarks/>
        public string FieldIdent {
            get {
                return this.fieldIdentField;
            }
            set {
                this.fieldIdentField = value;
            }
        }
        
        /// <remarks/>
        public Field MainField {
            get {
                return this.mainFieldField;
            }
            set {
                this.mainFieldField = value;
            }
        }
        
        /// <remarks/>
        public string FieldEntryNumber {
            get {
                return this.fieldEntryNumberField;
            }
            set {
                this.fieldEntryNumberField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime FieldActionDate {
            get {
                return this.fieldActionDateField;
            }
            set {
                this.fieldActionDateField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://egov.bg/RegiX/AV/TR/ActualStateResponseV2")]
    public partial class Field {
        
        private int groupIdField;
        
        private bool groupIdFieldSpecified;
        
        private string groupNameField;
        
        private int sectionIdField;
        
        private bool sectionIdFieldSpecified;
        
        private string sectionNameField;
        
        private FieldCodes mainFieldIdentField;
        
        private bool mainFieldIdentFieldSpecified;
        
        private string mainFieldCodeField;
        
        private string mainFieldNameField;
        
        /// <remarks/>
        public int GroupId {
            get {
                return this.groupIdField;
            }
            set {
                this.groupIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool GroupIdSpecified {
            get {
                return this.groupIdFieldSpecified;
            }
            set {
                this.groupIdFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public string GroupName {
            get {
                return this.groupNameField;
            }
            set {
                this.groupNameField = value;
            }
        }
        
        /// <remarks/>
        public int SectionId {
            get {
                return this.sectionIdField;
            }
            set {
                this.sectionIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool SectionIdSpecified {
            get {
                return this.sectionIdFieldSpecified;
            }
            set {
                this.sectionIdFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public string SectionName {
            get {
                return this.sectionNameField;
            }
            set {
                this.sectionNameField = value;
            }
        }
        
        /// <remarks/>
        public FieldCodes MainFieldIdent {
            get {
                return this.mainFieldIdentField;
            }
            set {
                this.mainFieldIdentField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool MainFieldIdentSpecified {
            get {
                return this.mainFieldIdentFieldSpecified;
            }
            set {
                this.mainFieldIdentFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public string MainFieldCode {
            get {
                return this.mainFieldCodeField;
            }
            set {
                this.mainFieldCodeField = value;
            }
        }
        
        /// <remarks/>
        public string MainFieldName {
            get {
                return this.mainFieldNameField;
            }
            set {
                this.mainFieldNameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://egov.bg/RegiX/AV/TR/ActualStateResponseV2")]
    public enum FieldCodes {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("00010")]
        Item00010,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("00011")]
        Item00011,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("00012")]
        Item00012,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("00020")]
        Item00020,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("00030")]
        Item00030,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("00040")]
        Item00040,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("00050")]
        Item00050,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("00051")]
        Item00051,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("00060")]
        Item00060,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("00061")]
        Item00061,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("00070")]
        Item00070,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("00071")]
        Item00071,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("00080")]
        Item00080,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("00090")]
        Item00090,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("00100")]
        Item00100,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("00101")]
        Item00101,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("00102")]
        Item00102,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("00110")]
        Item00110,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("00120")]
        Item00120,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("00121")]
        Item00121,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("00122")]
        Item00122,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("00123")]
        Item00123,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("00130")]
        Item00130,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("00131")]
        Item00131,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("00132")]
        Item00132,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("00133")]
        Item00133,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("00134")]
        Item00134,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("00140")]
        Item00140,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("00142")]
        Item00142,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("00143")]
        Item00143,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("00150")]
        Item00150,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("00151")]
        Item00151,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("00160")]
        Item00160,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("00161")]
        Item00161,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("00162")]
        Item00162,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("00170")]
        Item00170,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("00180")]
        Item00180,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("00190")]
        Item00190,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("00200")]
        Item00200,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("00201")]
        Item00201,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("00210")]
        Item00210,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("00220")]
        Item00220,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("00221")]
        Item00221,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("00222")]
        Item00222,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("00223")]
        Item00223,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("00224")]
        Item00224,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("00225")]
        Item00225,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("00230")]
        Item00230,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("00231")]
        Item00231,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("00232")]
        Item00232,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("00240")]
        Item00240,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("00241")]
        Item00241,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("00250")]
        Item00250,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("00251")]
        Item00251,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("00260")]
        Item00260,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("00270")]
        Item00270,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("00271")]
        Item00271,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("00272")]
        Item00272,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("00273")]
        Item00273,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("00280")]
        Item00280,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("00281")]
        Item00281,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("00290")]
        Item00290,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("00310")]
        Item00310,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("00311")]
        Item00311,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("00312")]
        Item00312,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("00320")]
        Item00320,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("00330")]
        Item00330,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("00340")]
        Item00340,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("00410")]
        Item00410,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("00420")]
        Item00420,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("00430")]
        Item00430,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("00440")]
        Item00440,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("00510")]
        Item00510,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("00511")]
        Item00511,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("00512")]
        Item00512,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("00520")]
        Item00520,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("00521")]
        Item00521,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("00530")]
        Item00530,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("00540")]
        Item00540,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("00541")]
        Item00541,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("00550")]
        Item00550,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("00600")]
        Item00600,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("00700")]
        Item00700,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("00701")]
        Item00701,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("00710")]
        Item00710,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("01000")]
        Item01000,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("01010")]
        Item01010,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("01020")]
        Item01020,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("01021")]
        Item01021,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("01030")]
        Item01030,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("01040")]
        Item01040,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("01050")]
        Item01050,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("01060")]
        Item01060,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("01070")]
        Item01070,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("01080")]
        Item01080,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("01090")]
        Item01090,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("01100")]
        Item01100,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("01110")]
        Item01110,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("01120")]
        Item01120,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("01130")]
        Item01130,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("01140")]
        Item01140,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("01150")]
        Item01150,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("01160")]
        Item01160,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("01170")]
        Item01170,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("02000")]
        Item02000,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("02010")]
        Item02010,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("02030")]
        Item02030,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("02050")]
        Item02050,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("02070")]
        Item02070,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("02080")]
        Item02080,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("02090")]
        Item02090,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("02100")]
        Item02100,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("02110")]
        Item02110,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("02120")]
        Item02120,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("02130")]
        Item02130,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("02140")]
        Item02140,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("02150")]
        Item02150,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("02160")]
        Item02160,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("02170")]
        Item02170,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("02180")]
        Item02180,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("02190")]
        Item02190,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("02200")]
        Item02200,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("02210")]
        Item02210,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("02220")]
        Item02220,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("02230")]
        Item02230,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("02240")]
        Item02240,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("02250")]
        Item02250,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("03000")]
        Item03000,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("03010")]
        Item03010,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("03030")]
        Item03030,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("03050")]
        Item03050,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("03060")]
        Item03060,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("03070")]
        Item03070,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("03080")]
        Item03080,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("03090")]
        Item03090,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("03100")]
        Item03100,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("03110")]
        Item03110,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("03120")]
        Item03120,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("03130")]
        Item03130,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("03140")]
        Item03140,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("03150")]
        Item03150,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("03160")]
        Item03160,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("03170")]
        Item03170,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("03180")]
        Item03180,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("03190")]
        Item03190,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("03200")]
        Item03200,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("03210")]
        Item03210,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("03220")]
        Item03220,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("03230")]
        Item03230,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("03240")]
        Item03240,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("03250")]
        Item03250,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("03251")]
        Item03251,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("03260")]
        Item03260,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("04000")]
        Item04000,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("04010")]
        Item04010,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("04030")]
        Item04030,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("04040")]
        Item04040,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("04041")]
        Item04041,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("04050")]
        Item04050,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("04060")]
        Item04060,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("04080")]
        Item04080,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("04090")]
        Item04090,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("04100")]
        Item04100,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("05010")]
        Item05010,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("05020")]
        Item05020,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("05030")]
        Item05030,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("05040")]
        Item05040,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("05050")]
        Item05050,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("05060")]
        Item05060,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("05300")]
        Item05300,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("05310")]
        Item05310,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("05320")]
        Item05320,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("05330")]
        Item05330,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("05340")]
        Item05340,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("05350")]
        Item05350,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("05360")]
        Item05360,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("05370")]
        Item05370,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("05371")]
        Item05371,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("05380")]
        Item05380,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("05381")]
        Item05381,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("05400")]
        Item05400,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("05500")]
        Item05500,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("05510")]
        Item05510,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("06000")]
        Item06000,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("06010")]
        Item06010,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("06020")]
        Item06020,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("07010")]
        Item07010,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("07020")]
        Item07020,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("07021")]
        Item07021,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("07030")]
        Item07030,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("07040")]
        Item07040,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("07050")]
        Item07050,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("07060")]
        Item07060,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("08010")]
        Item08010,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("08011")]
        Item08011,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("08020")]
        Item08020,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("08021")]
        Item08021,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("08030")]
        Item08030,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("08040")]
        Item08040,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("09010")]
        Item09010,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("09012")]
        Item09012,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("09013")]
        Item09013,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("09020")]
        Item09020,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("09021")]
        Item09021,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("09022")]
        Item09022,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("09023")]
        Item09023,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("09030")]
        Item09030,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("09032")]
        Item09032,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("09033")]
        Item09033,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("09040")]
        Item09040,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("09042")]
        Item09042,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("09043")]
        Item09043,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("09050")]
        Item09050,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("09052")]
        Item09052,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("09053")]
        Item09053,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("09060")]
        Item09060,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("09061")]
        Item09061,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("09062")]
        Item09062,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("09063")]
        Item09063,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("09064")]
        Item09064,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("09065")]
        Item09065,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("09070")]
        Item09070,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("09072")]
        Item09072,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("09073")]
        Item09073,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("09080")]
        Item09080,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("09082")]
        Item09082,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("09083")]
        Item09083,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("09090")]
        Item09090,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("09092")]
        Item09092,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("09093")]
        Item09093,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("09100")]
        Item09100,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("09102")]
        Item09102,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("09103")]
        Item09103,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("09110")]
        Item09110,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("09111")]
        Item09111,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("09112")]
        Item09112,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("09113")]
        Item09113,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("09114")]
        Item09114,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("09115")]
        Item09115,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("09120")]
        Item09120,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("09122")]
        Item09122,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("09123")]
        Item09123,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("09150")]
        Item09150,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("09151")]
        Item09151,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("09152")]
        Item09152,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("09153")]
        Item09153,
        
        /// <remarks/>
        X1080,
    }
}
