//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace SoapServiceNAPOOweb.Reference
{


    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace = "http://is.navet.government.bg/ws/", ConfigurationName = "Data")]
    public interface Data
    {

        [System.ServiceModel.OperationContractAttribute(Action = "urn:DataWSDL#getSPPOOList", ReplyAction = "*")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        getSPPOOListResponse getSPPOOList(getSPPOOListRequest request);

        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action = "urn:DataWSDL#getSPPOOList", ReplyAction = "*")]
        System.Threading.Tasks.Task<getSPPOOListResponse> getSPPOOListAsync(getSPPOOListRequest request);

        [System.ServiceModel.OperationContractAttribute(Action = "urn:DataWSDL#getCPOData", ReplyAction = "*")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        getCPODataResponse getCPOData(getCPODataRequest request);

        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action = "urn:DataWSDL#getCPOData", ReplyAction = "*")]
        System.Threading.Tasks.Task<getCPODataResponse> getCPODataAsync(getCPODataRequest request);

        [System.ServiceModel.OperationContractAttribute(Action = "urn:DataWSDL#getCipoData", ReplyAction = "*")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        getCipoDataResponse getCipoData(getCipoDataRequest request);

        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action = "urn:DataWSDL#getCipoData", ReplyAction = "*")]
        System.Threading.Tasks.Task<getCipoDataResponse> getCipoDataAsync(getCipoDataRequest request);

        [System.ServiceModel.OperationContractAttribute(Action = "urn:DataWSDL#getTrainers", ReplyAction = "*")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        getTrainersResponse getTrainers(getTrainersRequest request);

        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action = "urn:DataWSDL#getTrainers", ReplyAction = "*")]
        System.Threading.Tasks.Task<getTrainersResponse> getTrainersAsync(getTrainersRequest request);

        //[System.ServiceModel.OperationContractAttribute(Action = "urn:DataWSDL#getMTB", ReplyAction = "*")]
        //[System.ServiceModel.XmlSerializerFormatAttribute()]
        //getMTBResponse getMTB(getMTBRequest request);

        //// CODEGEN: Generating message contract since the operation has multiple return values.
        //[System.ServiceModel.OperationContractAttribute(Action = "urn:DataWSDL#getMTB", ReplyAction = "*")]
        //System.Threading.Tasks.Task<getMTBResponse> getMTBAsync(getMTBRequest request);

        [System.ServiceModel.OperationContractAttribute(Action = "urn:DataWSDL#checkSpecialityStatus", ReplyAction = "*")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        checkSpecialityStatusResponse checkSpecialityStatus(checkSpecialityStatusRequest request);

        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action = "urn:DataWSDL#checkSpecialityStatus", ReplyAction = "*")]
        System.Threading.Tasks.Task<checkSpecialityStatusResponse> checkSpecialityStatusAsync(checkSpecialityStatusRequest request);
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://is.navet.government.bg/ws/")]
    public partial class LoadNAPOOgetSPPOORequestType
    {

        private string usernameField;

        private string passwordField;

        private int activeField;

        /// <remarks/>
        public string username
        {
            get
            {
                return this.usernameField;
            }
            set
            {
                this.usernameField = value;
            }
        }

        /// <remarks/>
        public string password
        {
            get
            {
                return this.passwordField;
            }
            set
            {
                this.passwordField = value;
            }
        }

        /// <remarks/>
        public int active
        {
            get
            {
                return this.activeField;
            }
            set
            {
                this.activeField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://is.navet.government.bg/ws/")]
    public partial class NAPOOcheckSpecialityStatusData
    {

        private bool is_validField;

        /// <remarks/>
        public bool is_valid
        {
            get
            {
                return this.is_validField;
            }
            set
            {
                this.is_validField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://is.navet.government.bg/ws/")]
    public partial class LoadNAPOOgcheckSpecialityStatusDataResponseType
    {

        private bool statusField;

        private string messageField;

        private NAPOOcheckSpecialityStatusData[] dataField;

        /// <remarks/>
        public bool status
        {
            get
            {
                return this.statusField;
            }
            set
            {
                this.statusField = value;
            }
        }

        /// <remarks/>
        public string message
        {
            get
            {
                return this.messageField;
            }
            set
            {
                this.messageField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("entries")]
        public NAPOOcheckSpecialityStatusData[] data
        {
            get
            {
                return this.dataField;
            }
            set
            {
                this.dataField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://is.navet.government.bg/ws/")]
    public partial class LoadNAPOOcheckSpecialityStatusDataRequestType
    {

        private string usernameField;

        private string passwordField;

        private int licence_numberField;

        private string bulstatField;

        private int int_specialityField;

        /// <remarks/>
        public string username
        {
            get
            {
                return this.usernameField;
            }
            set
            {
                this.usernameField = value;
            }
        }

        /// <remarks/>
        public string password
        {
            get
            {
                return this.passwordField;
            }
            set
            {
                this.passwordField = value;
            }
        }

        /// <remarks/>
        public int licence_number
        {
            get
            {
                return this.licence_numberField;
            }
            set
            {
                this.licence_numberField = value;
            }
        }

        /// <remarks/>
        public string bulstat
        {
            get
            {
                return this.bulstatField;
            }
            set
            {
                this.bulstatField = value;
            }
        }

        /// <remarks/>
        public int int_speciality
        {
            get
            {
                return this.int_specialityField;
            }
            set
            {
                this.int_specialityField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://is.navet.government.bg/ws/")]
    public partial class NAPOOgetMTBData
    {

        private int idField;

        private string provider_premise_ekatteField;

        private string cityField;

        private string provider_premise_addressField;

        private string provider_premise_nameField;

        private string provider_premise_notesField;

        private int provider_idField;

        private int licence_numberField;

        private int provider_premise_speciality_usageField;

        private int post_codeField;

        /// <remarks/>
        public int id
        {
            get
            {
                return this.idField;
            }
            set
            {
                this.idField = value;
            }
        }

        /// <remarks/>
        public string provider_premise_ekatte
        {
            get
            {
                return this.provider_premise_ekatteField;
            }
            set
            {
                this.provider_premise_ekatteField = value;
            }
        }

        /// <remarks/>
        public string city
        {
            get
            {
                return this.cityField;
            }
            set
            {
                this.cityField = value;
            }
        }

        /// <remarks/>
        public string provider_premise_address
        {
            get
            {
                return this.provider_premise_addressField;
            }
            set
            {
                this.provider_premise_addressField = value;
            }
        }

        /// <remarks/>
        public string provider_premise_name
        {
            get
            {
                return this.provider_premise_nameField;
            }
            set
            {
                this.provider_premise_nameField = value;
            }
        }

        /// <remarks/>
        public string provider_premise_notes
        {
            get
            {
                return this.provider_premise_notesField;
            }
            set
            {
                this.provider_premise_notesField = value;
            }
        }

        /// <remarks/>
        public int provider_id
        {
            get
            {
                return this.provider_idField;
            }
            set
            {
                this.provider_idField = value;
            }
        }

        /// <remarks/>
        public int licence_number
        {
            get
            {
                return this.licence_numberField;
            }
            set
            {
                this.licence_numberField = value;
            }
        }

        /// <remarks/>
        public int provider_premise_speciality_usage
        {
            get
            {
                return this.provider_premise_speciality_usageField;
            }
            set
            {
                this.provider_premise_speciality_usageField = value;
            }
        }

        /// <remarks/>
        public int post_code
        {
            get
            {
                return this.post_codeField;
            }
            set
            {
                this.post_codeField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://is.navet.government.bg/ws/")]
    public partial class LoadNAPOOgetMTBDataResponseType
    {

        private bool statusField;

        private string messageField;

        private NAPOOgetMTBData[] dataField;

        /// <remarks/>
        public bool status
        {
            get
            {
                return this.statusField;
            }
            set
            {
                this.statusField = value;
            }
        }

        /// <remarks/>
        public string message
        {
            get
            {
                return this.messageField;
            }
            set
            {
                this.messageField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("entries")]
        public NAPOOgetMTBData[] data
        {
            get
            {
                return this.dataField;
            }
            set
            {
                this.dataField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://is.navet.government.bg/ws/")]
    public partial class LoadNAPOOgetMTBDataRequestType
    {

        private string usernameField;

        private string passwordField;

        private int licence_numberField;

        private string bulstatField;

        /// <remarks/>
        public string username
        {
            get
            {
                return this.usernameField;
            }
            set
            {
                this.usernameField = value;
            }
        }

        /// <remarks/>
        public string password
        {
            get
            {
                return this.passwordField;
            }
            set
            {
                this.passwordField = value;
            }
        }

        /// <remarks/>
        public int licence_number
        {
            get
            {
                return this.licence_numberField;
            }
            set
            {
                this.licence_numberField = value;
            }
        }

        /// <remarks/>
        public string bulstat
        {
            get
            {
                return this.bulstatField;
            }
            set
            {
                this.bulstatField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://is.navet.government.bg/ws/")]
    public partial class NAPOOgetTrainersData
    {

        private int idField;

        private string egnField;

        private string trainer_nameField;

        private int licence_numberField;

        private int vet_area_qualifiedField;

        private string vet_area_qualified_recodedField;

        private int area_idField;

        private string area_nameField;

        private int theory_practiceField;

        private string theory_practice_recodedField;

        /// <remarks/>
        public int id
        {
            get
            {
                return this.idField;
            }
            set
            {
                this.idField = value;
            }
        }

        /// <remarks/>
        public string egn
        {
            get
            {
                return this.egnField;
            }
            set
            {
                this.egnField = value;
            }
        }

        /// <remarks/>
        public string trainer_name
        {
            get
            {
                return this.trainer_nameField;
            }
            set
            {
                this.trainer_nameField = value;
            }
        }

        /// <remarks/>
        public int licence_number
        {
            get
            {
                return this.licence_numberField;
            }
            set
            {
                this.licence_numberField = value;
            }
        }

        /// <remarks/>
        public int vet_area_qualified
        {
            get
            {
                return this.vet_area_qualifiedField;
            }
            set
            {
                this.vet_area_qualifiedField = value;
            }
        }

        /// <remarks/>
        public string vet_area_qualified_recoded
        {
            get
            {
                return this.vet_area_qualified_recodedField;
            }
            set
            {
                this.vet_area_qualified_recodedField = value;
            }
        }

        /// <remarks/>
        public int area_id
        {
            get
            {
                return this.area_idField;
            }
            set
            {
                this.area_idField = value;
            }
        }

        /// <remarks/>
        public string area_name
        {
            get
            {
                return this.area_nameField;
            }
            set
            {
                this.area_nameField = value;
            }
        }

        /// <remarks/>
        public int theory_practice
        {
            get
            {
                return this.theory_practiceField;
            }
            set
            {
                this.theory_practiceField = value;
            }
        }

        /// <remarks/>
        public string theory_practice_recoded
        {
            get
            {
                return this.theory_practice_recodedField;
            }
            set
            {
                this.theory_practice_recodedField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://is.navet.government.bg/ws/")]
    public partial class LoadNAPOOgetTrainersDataResponseType
    {

        private bool statusField;

        private string messageField;

        private NAPOOgetTrainersData[] dataField;

        /// <remarks/>
        public bool status
        {
            get
            {
                return this.statusField;
            }
            set
            {
                this.statusField = value;
            }
        }

        /// <remarks/>
        public string message
        {
            get
            {
                return this.messageField;
            }
            set
            {
                this.messageField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("entries")]
        public NAPOOgetTrainersData[] data
        {
            get
            {
                return this.dataField;
            }
            set
            {
                this.dataField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://is.navet.government.bg/ws/")]
    public partial class LoadNAPOOgetTrainersDataRequestType
    {

        private string usernameField;

        private string passwordField;

        private int licence_numberField;

        private string bulstatField;

        private int int_areaField;

        /// <remarks/>
        public string username
        {
            get
            {
                return this.usernameField;
            }
            set
            {
                this.usernameField = value;
            }
        }

        /// <remarks/>
        public string password
        {
            get
            {
                return this.passwordField;
            }
            set
            {
                this.passwordField = value;
            }
        }

        /// <remarks/>
        public int licence_number
        {
            get
            {
                return this.licence_numberField;
            }
            set
            {
                this.licence_numberField = value;
            }
        }

        /// <remarks/>
        public string bulstat
        {
            get
            {
                return this.bulstatField;
            }
            set
            {
                this.bulstatField = value;
            }
        }

        /// <remarks/>
        public int int_area
        {
            get
            {
                return this.int_areaField;
            }
            set
            {
                this.int_areaField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://is.navet.government.bg/ws/")]
    public partial class NAPOOgetCipoData
    {

        private int provider_idField;

        private int provider_status_idField;

        private string provider_status_nameField;

        private int licence_numberField;

        private int provider_bulstatField;

        private string provider_ownerField;

        private string provider_managerField;

        private int licence_statusField;

        private string provider_cityField;

        private string provider_zip_codeField;

        private string provider_addressField;

        private string provider_phone1Field;

        private string provider_phone2Field;

        private string provider_faxField;

        private string provider_webField;

        private string provider_emailField;

        private string provider_contact_persField;

        private string contact_person_ekatte_nameField;

        private string provider_contact_pers_zipcodeField;

        private string provider_contact_pers_addressField;

        private string provider_contact_pers_phone1Field;

        private string provider_contact_pers_phone2Field;

        private string provider_contact_pers_faxField;

        private string provider_contact_pers_emailField;

        private bool bool_is_brraField;

        private string vc_provider_profileField;

        private string vc_provider_nameField;

        private System.Nullable<System.DateTime> provider_licence_dateField;

        /// <remarks/>
        public int provider_id
        {
            get
            {
                return this.provider_idField;
            }
            set
            {
                this.provider_idField = value;
            }
        }

        /// <remarks/>
        public int provider_status_id
        {
            get
            {
                return this.provider_status_idField;
            }
            set
            {
                this.provider_status_idField = value;
            }
        }

        /// <remarks/>
        public string provider_status_name
        {
            get
            {
                return this.provider_status_nameField;
            }
            set
            {
                this.provider_status_nameField = value;
            }
        }

        /// <remarks/>
        public int licence_number
        {
            get
            {
                return this.licence_numberField;
            }
            set
            {
                this.licence_numberField = value;
            }
        }

        /// <remarks/>
        public int provider_bulstat
        {
            get
            {
                return this.provider_bulstatField;
            }
            set
            {
                this.provider_bulstatField = value;
            }
        }

        /// <remarks/>
        public string provider_owner
        {
            get
            {
                return this.provider_ownerField;
            }
            set
            {
                this.provider_ownerField = value;
            }
        }

        /// <remarks/>
        public string provider_manager
        {
            get
            {
                return this.provider_managerField;
            }
            set
            {
                this.provider_managerField = value;
            }
        }

        /// <remarks/>
        public int licence_status
        {
            get
            {
                return this.licence_statusField;
            }
            set
            {
                this.licence_statusField = value;
            }
        }

        /// <remarks/>
        public string provider_city
        {
            get
            {
                return this.provider_cityField;
            }
            set
            {
                this.provider_cityField = value;
            }
        }

        /// <remarks/>
        public string provider_zip_code
        {
            get
            {
                return this.provider_zip_codeField;
            }
            set
            {
                this.provider_zip_codeField = value;
            }
        }

        /// <remarks/>
        public string provider_address
        {
            get
            {
                return this.provider_addressField;
            }
            set
            {
                this.provider_addressField = value;
            }
        }

        /// <remarks/>
        public string provider_phone1
        {
            get
            {
                return this.provider_phone1Field;
            }
            set
            {
                this.provider_phone1Field = value;
            }
        }

        /// <remarks/>
        public string provider_phone2
        {
            get
            {
                return this.provider_phone2Field;
            }
            set
            {
                this.provider_phone2Field = value;
            }
        }

        /// <remarks/>
        public string provider_fax
        {
            get
            {
                return this.provider_faxField;
            }
            set
            {
                this.provider_faxField = value;
            }
        }

        /// <remarks/>
        public string provider_web
        {
            get
            {
                return this.provider_webField;
            }
            set
            {
                this.provider_webField = value;
            }
        }

        /// <remarks/>
        public string provider_email
        {
            get
            {
                return this.provider_emailField;
            }
            set
            {
                this.provider_emailField = value;
            }
        }

        /// <remarks/>
        public string provider_contact_pers
        {
            get
            {
                return this.provider_contact_persField;
            }
            set
            {
                this.provider_contact_persField = value;
            }
        }

        /// <remarks/>
        public string contact_person_ekatte_name
        {
            get
            {
                return this.contact_person_ekatte_nameField;
            }
            set
            {
                this.contact_person_ekatte_nameField = value;
            }
        }

        /// <remarks/>
        public string provider_contact_pers_zipcode
        {
            get
            {
                return this.provider_contact_pers_zipcodeField;
            }
            set
            {
                this.provider_contact_pers_zipcodeField = value;
            }
        }

        /// <remarks/>
        public string provider_contact_pers_address
        {
            get
            {
                return this.provider_contact_pers_addressField;
            }
            set
            {
                this.provider_contact_pers_addressField = value;
            }
        }

        /// <remarks/>
        public string provider_contact_pers_phone1
        {
            get
            {
                return this.provider_contact_pers_phone1Field;
            }
            set
            {
                this.provider_contact_pers_phone1Field = value;
            }
        }

        /// <remarks/>
        public string provider_contact_pers_phone2
        {
            get
            {
                return this.provider_contact_pers_phone2Field;
            }
            set
            {
                this.provider_contact_pers_phone2Field = value;
            }
        }

        /// <remarks/>
        public string provider_contact_pers_fax
        {
            get
            {
                return this.provider_contact_pers_faxField;
            }
            set
            {
                this.provider_contact_pers_faxField = value;
            }
        }

        /// <remarks/>
        public string provider_contact_pers_email
        {
            get
            {
                return this.provider_contact_pers_emailField;
            }
            set
            {
                this.provider_contact_pers_emailField = value;
            }
        }

        /// <remarks/>
        public bool bool_is_brra
        {
            get
            {
                return this.bool_is_brraField;
            }
            set
            {
                this.bool_is_brraField = value;
            }
        }

        /// <remarks/>
        public string vc_provider_profile
        {
            get
            {
                return this.vc_provider_profileField;
            }
            set
            {
                this.vc_provider_profileField = value;
            }
        }

        /// <remarks/>
        public string vc_provider_name
        {
            get
            {
                return this.vc_provider_nameField;
            }
            set
            {
                this.vc_provider_nameField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType = "date", IsNullable = true)]
        public System.Nullable<System.DateTime> provider_licence_date
        {
            get
            {
                return this.provider_licence_dateField;
            }
            set
            {
                this.provider_licence_dateField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://is.navet.government.bg/ws/")]
    public partial class LoadNAPOOgetCipoDataResponseType
    {

        private bool statusField;

        private string messageField;

        private NAPOOgetCipoData[] dataField;

        /// <remarks/>
        public bool status
        {
            get
            {
                return this.statusField;
            }
            set
            {
                this.statusField = value;
            }
        }

        /// <remarks/>
        public string message
        {
            get
            {
                return this.messageField;
            }
            set
            {
                this.messageField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("entries")]
        public NAPOOgetCipoData[] data
        {
            get
            {
                return this.dataField;
            }
            set
            {
                this.dataField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://is.navet.government.bg/ws/")]
    public partial class LoadNAPOOgetCipoDataRequestType
    {

        private string usernameField;

        private string passwordField;

        private int licence_numberField;

        private string bulstatField;

        /// <remarks/>
        public string username
        {
            get
            {
                return this.usernameField;
            }
            set
            {
                this.usernameField = value;
            }
        }

        /// <remarks/>
        public string password
        {
            get
            {
                return this.passwordField;
            }
            set
            {
                this.passwordField = value;
            }
        }

        /// <remarks/>
        public int licence_number
        {
            get
            {
                return this.licence_numberField;
            }
            set
            {
                this.licence_numberField = value;
            }
        }

        /// <remarks/>
        public string bulstat
        {
            get
            {
                return this.bulstatField;
            }
            set
            {
                this.bulstatField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://is.navet.government.bg/ws/")]
    public partial class NAPOOgetCpoData
    {

        private int provider_idField;

        private int provider_status_idField;

        private string provider_status_nameField;

        private int licence_numberField;

        private int provider_bulstatField;

        private string provider_ownerField;

        private string provider_managerField;

        private int licence_statusField;

        private string provider_cityField;

        private string provider_zip_codeField;

        private string provider_addressField;

        private string provider_phone1Field;

        private string provider_phone2Field;

        private string provider_faxField;

        private string provider_webField;

        private string provider_emailField;

        private string provider_contact_persField;

        private string contact_person_ekatte_nameField;

        private int provider_contact_pers_zipcodeField;

        private string provider_contact_pers_addressField;

        private string provider_contact_pers_phone1Field;

        private string provider_contact_pers_phone2Field;

        private string provider_contact_pers_faxField;

        private string provider_contact_pers_emailField;

        private bool bool_is_brraField;

        private string vc_provider_profileField;

        private string vc_provider_nameField;

        private string provider_licence_dateField;

        private int vet_profession_idField;

        private int vet_profession_numberField;

        private string vet_profession_nameField;

        private bool profession_is_validField;

        private int vet_speciality_idField;

        private int vet_speciality_numberField;

        private string vet_speciality_nameField;

        private string vet_speciality_vqsField;

        private bool speciality_is_validField;

        private string speciality_date_startField;

        private string speciality_date_endField;

        private string speciality_date_licenceField;

        private bool provider_spec_is_validField;

        /// <remarks/>
        public int provider_id
        {
            get
            {
                return this.provider_idField;
            }
            set
            {
                this.provider_idField = value;
            }
        }

        /// <remarks/>
        public int provider_status_id
        {
            get
            {
                return this.provider_status_idField;
            }
            set
            {
                this.provider_status_idField = value;
            }
        }

        /// <remarks/>
        public string provider_status_name
        {
            get
            {
                return this.provider_status_nameField;
            }
            set
            {
                this.provider_status_nameField = value;
            }
        }

        /// <remarks/>
        public int licence_number
        {
            get
            {
                return this.licence_numberField;
            }
            set
            {
                this.licence_numberField = value;
            }
        }

        /// <remarks/>
        public int provider_bulstat
        {
            get
            {
                return this.provider_bulstatField;
            }
            set
            {
                this.provider_bulstatField = value;
            }
        }

        /// <remarks/>
        public string provider_owner
        {
            get
            {
                return this.provider_ownerField;
            }
            set
            {
                this.provider_ownerField = value;
            }
        }

        /// <remarks/>
        public string provider_manager
        {
            get
            {
                return this.provider_managerField;
            }
            set
            {
                this.provider_managerField = value;
            }
        }

        /// <remarks/>
        public int licence_status
        {
            get
            {
                return this.licence_statusField;
            }
            set
            {
                this.licence_statusField = value;
            }
        }

        /// <remarks/>
        public string provider_city
        {
            get
            {
                return this.provider_cityField;
            }
            set
            {
                this.provider_cityField = value;
            }
        }

        /// <remarks/>
        public string provider_zip_code
        {
            get
            {
                return this.provider_zip_codeField;
            }
            set
            {
                this.provider_zip_codeField = value;
            }
        }

        /// <remarks/>
        public string provider_address
        {
            get
            {
                return this.provider_addressField;
            }
            set
            {
                this.provider_addressField = value;
            }
        }

        /// <remarks/>
        public string provider_phone1
        {
            get
            {
                return this.provider_phone1Field;
            }
            set
            {
                this.provider_phone1Field = value;
            }
        }

        /// <remarks/>
        public string provider_phone2
        {
            get
            {
                return this.provider_phone2Field;
            }
            set
            {
                this.provider_phone2Field = value;
            }
        }

        /// <remarks/>
        public string provider_fax
        {
            get
            {
                return this.provider_faxField;
            }
            set
            {
                this.provider_faxField = value;
            }
        }

        /// <remarks/>
        public string provider_web
        {
            get
            {
                return this.provider_webField;
            }
            set
            {
                this.provider_webField = value;
            }
        }

        /// <remarks/>
        public string provider_email
        {
            get
            {
                return this.provider_emailField;
            }
            set
            {
                this.provider_emailField = value;
            }
        }

        /// <remarks/>
        public string provider_contact_pers
        {
            get
            {
                return this.provider_contact_persField;
            }
            set
            {
                this.provider_contact_persField = value;
            }
        }

        /// <remarks/>
        public string contact_person_ekatte_name
        {
            get
            {
                return this.contact_person_ekatte_nameField;
            }
            set
            {
                this.contact_person_ekatte_nameField = value;
            }
        }

        /// <remarks/>
        public int provider_contact_pers_zipcode
        {
            get
            {
                return this.provider_contact_pers_zipcodeField;
            }
            set
            {
                this.provider_contact_pers_zipcodeField = value;
            }
        }

        /// <remarks/>
        public string provider_contact_pers_address
        {
            get
            {
                return this.provider_contact_pers_addressField;
            }
            set
            {
                this.provider_contact_pers_addressField = value;
            }
        }

        /// <remarks/>
        public string provider_contact_pers_phone1
        {
            get
            {
                return this.provider_contact_pers_phone1Field;
            }
            set
            {
                this.provider_contact_pers_phone1Field = value;
            }
        }

        /// <remarks/>
        public string provider_contact_pers_phone2
        {
            get
            {
                return this.provider_contact_pers_phone2Field;
            }
            set
            {
                this.provider_contact_pers_phone2Field = value;
            }
        }

        /// <remarks/>
        public string provider_contact_pers_fax
        {
            get
            {
                return this.provider_contact_pers_faxField;
            }
            set
            {
                this.provider_contact_pers_faxField = value;
            }
        }

        /// <remarks/>
        public string provider_contact_pers_email
        {
            get
            {
                return this.provider_contact_pers_emailField;
            }
            set
            {
                this.provider_contact_pers_emailField = value;
            }
        }

        /// <remarks/>
        public bool bool_is_brra
        {
            get
            {
                return this.bool_is_brraField;
            }
            set
            {
                this.bool_is_brraField = value;
            }
        }

        /// <remarks/>
        public string vc_provider_profile
        {
            get
            {
                return this.vc_provider_profileField;
            }
            set
            {
                this.vc_provider_profileField = value;
            }
        }

        /// <remarks/>
        public string vc_provider_name
        {
            get
            {
                return this.vc_provider_nameField;
            }
            set
            {
                this.vc_provider_nameField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string provider_licence_date
        {
            get
            {
                return this.provider_licence_dateField;
            }
            set
            {
                this.provider_licence_dateField = value;
            }
        }

        /// <remarks/>
        public int vet_profession_id
        {
            get
            {
                return this.vet_profession_idField;
            }
            set
            {
                this.vet_profession_idField = value;
            }
        }

        /// <remarks/>
        public int vet_profession_number
        {
            get
            {
                return this.vet_profession_numberField;
            }
            set
            {
                this.vet_profession_numberField = value;
            }
        }

        /// <remarks/>
        public string vet_profession_name
        {
            get
            {
                return this.vet_profession_nameField;
            }
            set
            {
                this.vet_profession_nameField = value;
            }
        }

        /// <remarks/>
        public bool profession_is_valid
        {
            get
            {
                return this.profession_is_validField;
            }
            set
            {
                this.profession_is_validField = value;
            }
        }

        /// <remarks/>
        public int vet_speciality_id
        {
            get
            {
                return this.vet_speciality_idField;
            }
            set
            {
                this.vet_speciality_idField = value;
            }
        }

        /// <remarks/>
        public int vet_speciality_number
        {
            get
            {
                return this.vet_speciality_numberField;
            }
            set
            {
                this.vet_speciality_numberField = value;
            }
        }

        /// <remarks/>
        public string vet_speciality_name
        {
            get
            {
                return this.vet_speciality_nameField;
            }
            set
            {
                this.vet_speciality_nameField = value;
            }
        }

        /// <remarks/>
        public string vet_speciality_vqs
        {
            get
            {
                return this.vet_speciality_vqsField;
            }
            set
            {
                this.vet_speciality_vqsField = value;
            }
        }

        /// <remarks/>
        public bool speciality_is_valid
        {
            get
            {
                return this.speciality_is_validField;
            }
            set
            {
                this.speciality_is_validField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string speciality_date_start
        {
            get
            {
                return this.speciality_date_startField;
            }
            set
            {
                this.speciality_date_startField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string speciality_date_end
        {
            get
            {
                return this.speciality_date_endField;
            }
            set
            {
                this.speciality_date_endField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string speciality_date_licence
        {
            get
            {
                return this.speciality_date_licenceField;
            }
            set
            {
                this.speciality_date_licenceField = value;
            }
        }

        /// <remarks/>
        public bool provider_spec_is_valid
        {
            get
            {
                return this.provider_spec_is_validField;
            }
            set
            {
                this.provider_spec_is_validField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://is.navet.government.bg/ws/")]
    public partial class LoadNAPOOgetCpoDataResponseType
    {

        private bool statusField;

        private string messageField;

        private NAPOOgetCpoData[] dataField;

        /// <remarks/>
        public bool status
        {
            get
            {
                return this.statusField;
            }
            set
            {
                this.statusField = value;
            }
        }

        /// <remarks/>
        public string message
        {
            get
            {
                return this.messageField;
            }
            set
            {
                this.messageField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("entries")]
        public NAPOOgetCpoData[] data
        {
            get
            {
                return this.dataField;
            }
            set
            {
                this.dataField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://is.navet.government.bg/ws/")]
    public partial class LoadNAPOOgetCpoDataRequestType
    {

        private string usernameField;

        private string passwordField;

        private int licence_numberField;

        private string bulstatField;

        /// <remarks/>
        public string username
        {
            get
            {
                return this.usernameField;
            }
            set
            {
                this.usernameField = value;
            }
        }

        /// <remarks/>
        public string password
        {
            get
            {
                return this.passwordField;
            }
            set
            {
                this.passwordField = value;
            }
        }

        /// <remarks/>
        public int licence_number
        {
            get
            {
                return this.licence_numberField;
            }
            set
            {
                this.licence_numberField = value;
            }
        }

        /// <remarks/>
        public string bulstat
        {
            get
            {
                return this.bulstatField;
            }
            set
            {
                this.bulstatField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://is.navet.government.bg/ws/")]
    public partial class NAPOOgetSPPOO
    {

        private int vet_group_idField;

        private int vet_group_numberField;

        private string vet_group_nameField;

        private bool group_is_validField;

        private int vet_area_idField;

        private int vet_area_numberField;

        private string vet_area_nameField;

        private bool area_is_validField;

        private int vet_profession_idField;

        private int vet_profession_numberField;

        private string vet_profession_nameField;

        private bool profession_is_validField;

        private int vet_speciality_idField;

        private int vet_speciality_numberField;

        private string vet_speciality_nameField;

        private string vet_speciality_vqsField;

        private bool speciality_is_validField;

        private System.Nullable<System.DateTime> speciality_start_dateField;

        private System.Nullable<System.DateTime> speciality_end_dateField;

        /// <remarks/>
        public int vet_group_id
        {
            get
            {
                return this.vet_group_idField;
            }
            set
            {
                this.vet_group_idField = value;
            }
        }

        /// <remarks/>
        public int vet_group_number
        {
            get
            {
                return this.vet_group_numberField;
            }
            set
            {
                this.vet_group_numberField = value;
            }
        }

        /// <remarks/>
        public string vet_group_name
        {
            get
            {
                return this.vet_group_nameField;
            }
            set
            {
                this.vet_group_nameField = value;
            }
        }

        /// <remarks/>
        public bool group_is_valid
        {
            get
            {
                return this.group_is_validField;
            }
            set
            {
                this.group_is_validField = value;
            }
        }

        /// <remarks/>
        public int vet_area_id
        {
            get
            {
                return this.vet_area_idField;
            }
            set
            {
                this.vet_area_idField = value;
            }
        }

        /// <remarks/>
        public int vet_area_number
        {
            get
            {
                return this.vet_area_numberField;
            }
            set
            {
                this.vet_area_numberField = value;
            }
        }

        /// <remarks/>
        public string vet_area_name
        {
            get
            {
                return this.vet_area_nameField;
            }
            set
            {
                this.vet_area_nameField = value;
            }
        }

        /// <remarks/>
        public bool area_is_valid
        {
            get
            {
                return this.area_is_validField;
            }
            set
            {
                this.area_is_validField = value;
            }
        }

        /// <remarks/>
        public int vet_profession_id
        {
            get
            {
                return this.vet_profession_idField;
            }
            set
            {
                this.vet_profession_idField = value;
            }
        }

        /// <remarks/>
        public int vet_profession_number
        {
            get
            {
                return this.vet_profession_numberField;
            }
            set
            {
                this.vet_profession_numberField = value;
            }
        }

        /// <remarks/>
        public string vet_profession_name
        {
            get
            {
                return this.vet_profession_nameField;
            }
            set
            {
                this.vet_profession_nameField = value;
            }
        }

        /// <remarks/>
        public bool profession_is_valid
        {
            get
            {
                return this.profession_is_validField;
            }
            set
            {
                this.profession_is_validField = value;
            }
        }

        /// <remarks/>
        public int vet_speciality_id
        {
            get
            {
                return this.vet_speciality_idField;
            }
            set
            {
                this.vet_speciality_idField = value;
            }
        }

        /// <remarks/>
        public int vet_speciality_number
        {
            get
            {
                return this.vet_speciality_numberField;
            }
            set
            {
                this.vet_speciality_numberField = value;
            }
        }

        /// <remarks/>
        public string vet_speciality_name
        {
            get
            {
                return this.vet_speciality_nameField;
            }
            set
            {
                this.vet_speciality_nameField = value;
            }
        }

        /// <remarks/>
        public string vet_speciality_vqs
        {
            get
            {
                return this.vet_speciality_vqsField;
            }
            set
            {
                this.vet_speciality_vqsField = value;
            }
        }

        /// <remarks/>
        public bool speciality_is_valid
        {
            get
            {
                return this.speciality_is_validField;
            }
            set
            {
                this.speciality_is_validField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType = "date", IsNullable = true)]
        public System.Nullable<System.DateTime> speciality_start_date
        {
            get
            {
                return this.speciality_start_dateField;
            }
            set
            {
                this.speciality_start_dateField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType = "date", IsNullable = true)]
        public System.Nullable<System.DateTime> speciality_end_date
        {
            get
            {
                return this.speciality_end_dateField;
            }
            set
            {
                this.speciality_end_dateField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://is.navet.government.bg/ws/")]
    public partial class LoadNAPOOgetSPPOOResponseType
    {

        private bool statusField;

        private string messageField;

        private NAPOOgetSPPOO[] dataField;

        /// <remarks/>
        public bool status
        {
            get
            {
                return this.statusField;
            }
            set
            {
                this.statusField = value;
            }
        }

        /// <remarks/>
        public string message
        {
            get
            {
                return this.messageField;
            }
            set
            {
                this.messageField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("entries")]
        public NAPOOgetSPPOO[] data
        {
            get
            {
                return this.dataField;
            }
            set
            {
                this.dataField = value;
            }
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName = "getSPPOOList", WrapperNamespace = "urn:DataWSDL#getSPPOOList", IsWrapped = true)]
    public partial class getSPPOOListRequest
    {

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "", Order = 0)]
        public LoadNAPOOgetSPPOORequestType param;

        public getSPPOOListRequest()
        {
        }

        public getSPPOOListRequest(LoadNAPOOgetSPPOORequestType param)
        {
            this.param = param;
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName = "getSPPOOListResponse", WrapperNamespace = "urn:DataWSDL#getSPPOOList", IsWrapped = true)]
    public partial class getSPPOOListResponse
    {

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "", Order = 0)]
        public LoadNAPOOgetSPPOOResponseType param;

        public getSPPOOListResponse()
        {
        }

        public getSPPOOListResponse(LoadNAPOOgetSPPOOResponseType param)
        {
            this.param = param;
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName = "getCPOData", WrapperNamespace = "urn:DataWSDL#getCPOData", IsWrapped = true)]
    public partial class getCPODataRequest
    {

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "", Order = 0)]
        public LoadNAPOOgetCpoDataRequestType param;

        public getCPODataRequest()
        {
        }

        public getCPODataRequest(LoadNAPOOgetCpoDataRequestType param)
        {
            this.param = param;
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName = "getCPODataResponse", WrapperNamespace = "urn:DataWSDL#getCPOData", IsWrapped = true)]
    public partial class getCPODataResponse
    {

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "", Order = 0)]
        public LoadNAPOOgetCpoDataResponseType param;

        public getCPODataResponse()
        {
        }

        public getCPODataResponse(LoadNAPOOgetCpoDataResponseType param)
        {
            this.param = param;
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName = "getCipoData", WrapperNamespace = "urn:DataWSDL#getCipoData", IsWrapped = true)]
    public partial class getCipoDataRequest
    {

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "", Order = 0)]
        public LoadNAPOOgetCipoDataRequestType param;

        public getCipoDataRequest()
        {
        }

        public getCipoDataRequest(LoadNAPOOgetCipoDataRequestType param)
        {
            this.param = param;
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName = "getCipoDataResponse", WrapperNamespace = "urn:DataWSDL#getCipoData", IsWrapped = true)]
    public partial class getCipoDataResponse
    {

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "", Order = 0)]
        public LoadNAPOOgetCipoDataResponseType param;

        public getCipoDataResponse()
        {
        }

        public getCipoDataResponse(LoadNAPOOgetCipoDataResponseType param)
        {
            this.param = param;
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName = "getTrainers", WrapperNamespace = "urn:DataWSDL#getTrainers", IsWrapped = true)]
    public partial class getTrainersRequest
    {

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "", Order = 0)]
        public LoadNAPOOgetTrainersDataRequestType param;

        public getTrainersRequest()
        {
        }

        public getTrainersRequest(LoadNAPOOgetTrainersDataRequestType param)
        {
            this.param = param;
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName = "getTrainersResponse", WrapperNamespace = "urn:DataWSDL#getTrainers", IsWrapped = true)]
    public partial class getTrainersResponse
    {

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "", Order = 0)]
        public LoadNAPOOgetTrainersDataResponseType param;

        public getTrainersResponse()
        {
        }

        public getTrainersResponse(LoadNAPOOgetTrainersDataResponseType param)
        {
            this.param = param;
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName = "getMTB", WrapperNamespace = "urn:DataWSDL#getMTB", IsWrapped = true)]
    public partial class getMTBRequest
    {

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "", Order = 0)]
        public LoadNAPOOgetMTBDataRequestType param;

        public getMTBRequest()
        {
        }

        public getMTBRequest(LoadNAPOOgetMTBDataRequestType param)
        {
            this.param = param;
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName = "getMTBResponse", WrapperNamespace = "urn:DataWSDL#getMTB", IsWrapped = true)]
    public partial class getMTBResponse
    {

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "", Order = 0)]
        public LoadNAPOOgetMTBDataResponseType param;

        public getMTBResponse()
        {
        }

        public getMTBResponse(LoadNAPOOgetMTBDataResponseType param)
        {
            this.param = param;
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName = "checkSpecialityStatus", WrapperNamespace = "urn:DataWSDL#checkSpecialityStatus", IsWrapped = true)]
    public partial class checkSpecialityStatusRequest
    {

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "", Order = 0)]
        public LoadNAPOOcheckSpecialityStatusDataRequestType param;

        public checkSpecialityStatusRequest()
        {
        }

        public checkSpecialityStatusRequest(LoadNAPOOcheckSpecialityStatusDataRequestType param)
        {
            this.param = param;
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName = "checkSpecialityStatusResponse", WrapperNamespace = "urn:DataWSDL#checkSpecialityStatus", IsWrapped = true)]
    public partial class checkSpecialityStatusResponse
    {

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "", Order = 0)]
        public LoadNAPOOgcheckSpecialityStatusDataResponseType param;

        public checkSpecialityStatusResponse()
        {
        }

        public checkSpecialityStatusResponse(LoadNAPOOgcheckSpecialityStatusDataResponseType param)
        {
            this.param = param;
        }
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface DataChannel : Data, System.ServiceModel.IClientChannel
    {
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class DataClient : System.ServiceModel.ClientBase<Data>, Data
    {

        public DataClient()
        {
        }

        public DataClient(string endpointConfigurationName) :
                base(endpointConfigurationName)
        {
        }

        public DataClient(string endpointConfigurationName, string remoteAddress) :
                base(endpointConfigurationName, remoteAddress)
        {
        }

        public DataClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) :
                base(endpointConfigurationName, remoteAddress)
        {
        }

        public DataClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) :
                base(binding, remoteAddress)
        {
        }

        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        getSPPOOListResponse Data.getSPPOOList(getSPPOOListRequest request)
        {
            return base.Channel.getSPPOOList(request);
        }

        public LoadNAPOOgetSPPOOResponseType getSPPOOList(LoadNAPOOgetSPPOORequestType param)
        {
            getSPPOOListRequest inValue = new getSPPOOListRequest();
            inValue.param = param;
            getSPPOOListResponse retVal = ((Data)(this)).getSPPOOList(inValue);
            return retVal.param;
        }

        public System.Threading.Tasks.Task<getSPPOOListResponse> getSPPOOListAsync(getSPPOOListRequest request)
        {
            return base.Channel.getSPPOOListAsync(request);
        }

        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        getCPODataResponse Data.getCPOData(getCPODataRequest request)
        {
            return base.Channel.getCPOData(request);
        }

        public LoadNAPOOgetCpoDataResponseType getCPOData(LoadNAPOOgetCpoDataRequestType param)
        {
            getCPODataRequest inValue = new getCPODataRequest();
            inValue.param = param;
            getCPODataResponse retVal = ((Data)(this)).getCPOData(inValue);
            return retVal.param;
        }

        public System.Threading.Tasks.Task<getCPODataResponse> getCPODataAsync(getCPODataRequest request)
        {
            return base.Channel.getCPODataAsync(request);
        }

        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        getCipoDataResponse Data.getCipoData(getCipoDataRequest request)
        {
            return base.Channel.getCipoData(request);
        }

        public LoadNAPOOgetCipoDataResponseType getCipoData(LoadNAPOOgetCipoDataRequestType param)
        {
            getCipoDataRequest inValue = new getCipoDataRequest();
            inValue.param = param;
            getCipoDataResponse retVal = ((Data)(this)).getCipoData(inValue);
            return retVal.param;
        }

        public System.Threading.Tasks.Task<getCipoDataResponse> getCipoDataAsync(getCipoDataRequest request)
        {
            return base.Channel.getCipoDataAsync(request);
        }

        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        getTrainersResponse Data.getTrainers(getTrainersRequest request)
        {
            return base.Channel.getTrainers(request);
        }

        public LoadNAPOOgetTrainersDataResponseType getTrainers(LoadNAPOOgetTrainersDataRequestType param)
        {
            getTrainersRequest inValue = new getTrainersRequest();
            inValue.param = param;
            getTrainersResponse retVal = ((Data)(this)).getTrainers(inValue);
            return retVal.param;
        }

        public System.Threading.Tasks.Task<getTrainersResponse> getTrainersAsync(getTrainersRequest request)
        {
            return base.Channel.getTrainersAsync(request);
        }

        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        getMTBResponse Data.getMTB(getMTBRequest request)
        {
            return base.Channel.getMTB(request);
        }

        public LoadNAPOOgetMTBDataResponseType getMTB(LoadNAPOOgetMTBDataRequestType param)
        {
            getMTBRequest inValue = new getMTBRequest();
            inValue.param = param;
            getMTBResponse retVal = ((Data)(this)).getMTB(inValue);
            return retVal.param;
        }

        public System.Threading.Tasks.Task<getMTBResponse> getMTBAsync(getMTBRequest request)
        {
            return base.Channel.getMTBAsync(request);
        }

        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        checkSpecialityStatusResponse Data.checkSpecialityStatus(checkSpecialityStatusRequest request)
        {
            return base.Channel.checkSpecialityStatus(request);
        }

        public LoadNAPOOgcheckSpecialityStatusDataResponseType checkSpecialityStatus(LoadNAPOOcheckSpecialityStatusDataRequestType param)
        {
            checkSpecialityStatusRequest inValue = new checkSpecialityStatusRequest();
            inValue.param = param;
            checkSpecialityStatusResponse retVal = ((Data)(this)).checkSpecialityStatus(inValue);
            return retVal.param;
        }

        public System.Threading.Tasks.Task<checkSpecialityStatusResponse> checkSpecialityStatusAsync(checkSpecialityStatusRequest request)
        {
            return base.Channel.checkSpecialityStatusAsync(request);
        }
    }
}