//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by xsd, Version=4.8.3928.0.
// 
namespace RegiX.Class.NKPD.GetNKPDAllData
{
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://egov.bg/RegiX/MTSP/NKPD/AllNKPDDataResponse")]
    [System.Xml.Serialization.XmlRootAttribute("AllNKPDDataResponse", Namespace="http://egov.bg/RegiX/MTSP/NKPD/AllNKPDDataResponse", IsNullable=false)]
    public partial class AllNKPDDataType {
        
        private string versionNameField;
        
        private System.DateTime validDateField;
        
        private bool validDateFieldSpecified;
        
        private NKPDEntry[] nKPDField;
        
        /// <remarks/>
        public string VersionName {
            get {
                return this.versionNameField;
            }
            set {
                this.versionNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date")]
        public System.DateTime ValidDate {
            get {
                return this.validDateField;
            }
            set {
                this.validDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ValidDateSpecified {
            get {
                return this.validDateFieldSpecified;
            }
            set {
                this.validDateFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("NKPD")]
        public NKPDEntry[] NKPD {
            get {
                return this.nKPDField;
            }
            set {
                this.nKPDField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://egov.bg/RegiX/MTSP/NKPD")]
    public partial class NKPDEntry {
        
        private NKPDType typeField;
        
        private bool typeFieldSpecified;
        
        private string codeField;
        
        private string nameField;
        
        private string classCodeField;
        
        private string subclassCodeField;
        
        private string groupCodeField;
        
        private string individualGroupCodeField;
        
        private string educationLevelCodeField;
        
        /// <remarks/>
        public NKPDType Type {
            get {
                return this.typeField;
            }
            set {
                this.typeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool TypeSpecified {
            get {
                return this.typeFieldSpecified;
            }
            set {
                this.typeFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public string Code {
            get {
                return this.codeField;
            }
            set {
                this.codeField = value;
            }
        }
        
        /// <remarks/>
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        public string ClassCode {
            get {
                return this.classCodeField;
            }
            set {
                this.classCodeField = value;
            }
        }
        
        /// <remarks/>
        public string SubclassCode {
            get {
                return this.subclassCodeField;
            }
            set {
                this.subclassCodeField = value;
            }
        }
        
        /// <remarks/>
        public string GroupCode {
            get {
                return this.groupCodeField;
            }
            set {
                this.groupCodeField = value;
            }
        }
        
        /// <remarks/>
        public string IndividualGroupCode {
            get {
                return this.individualGroupCodeField;
            }
            set {
                this.individualGroupCodeField = value;
            }
        }
        
        /// <remarks/>
        public string EducationLevelCode {
            get {
                return this.educationLevelCodeField;
            }
            set {
                this.educationLevelCodeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://egov.bg/RegiX/MTSP/NKPD")]
    public enum NKPDType {
        
        /// <remarks/>
        @class,
        
        /// <remarks/>
        subClass,
        
        /// <remarks/>
        group,
        
        /// <remarks/>
        individualGroup,
        
        /// <remarks/>
        nkpd,
    }
}
