//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class LoginRegisterPage {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal LoginRegisterPage() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("eAuth.Resources.LoginRegisterPage", typeof(LoginRegisterPage).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Тест на Request.
        /// </summary>
        public static string LoginTestRequest {
            get {
                return ResourceManager.GetString("LoginTestRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вход с Квалифициран Електронен Подпис.
        /// </summary>
        public static string LoginWithKep {
            get {
                return ResourceManager.GetString("LoginWithKep", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Стартира се процес по електронна автентикация.
        /// </summary>
        public static string MessageStartingCertificateAuth {
            get {
                return ResourceManager.GetString("MessageStartingCertificateAuth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RelayState.
        /// </summary>
        public static string TestRequestRelayState {
            get {
                return ResourceManager.GetString("TestRequestRelayState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SamlRequest.
        /// </summary>
        public static string TestRequestSamlRequest {
            get {
                return ResourceManager.GetString("TestRequestSamlRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Неуспешен вход в системата с КЕП!.
        /// </summary>
        public static string TitleKepAuthFailed {
            get {
                return ResourceManager.GetString("TitleKepAuthFailed", resourceCulture);
            }
        }
    }
}
