//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DocuServiceReference
{
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://reg.docu.indexbg.com/")]
    public partial class DocuServiceFault
    {
        
        private string messageField;
        
        private string errorDetailField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string message
        {
            get
            {
                return this.messageField;
            }
            set
            {
                this.messageField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string errorDetail
        {
            get
            {
                return this.errorDetailField;
            }
            set
            {
                this.errorDetailField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://reg.docu.indexbg.com/")]
    public partial class FileData
    {
        
        private int fileIDField;
        
        private bool fileIDFieldSpecified;
        
        private string filenameField;
        
        private string contentTypeField;
        
        private byte[] binaryContentField;
        
        private bool signedField;
        
        private bool signedFieldSpecified;
        
        private bool personalDataField;
        
        private bool personalDataFieldSpecified;
        
        private bool officialField;
        
        private bool officialFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public int FileID
        {
            get
            {
                return this.fileIDField;
            }
            set
            {
                this.fileIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool FileIDSpecified
        {
            get
            {
                return this.fileIDFieldSpecified;
            }
            set
            {
                this.fileIDFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string Filename
        {
            get
            {
                return this.filenameField;
            }
            set
            {
                this.filenameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string ContentType
        {
            get
            {
                return this.contentTypeField;
            }
            set
            {
                this.contentTypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="base64Binary", Order=3)]
        public byte[] BinaryContent
        {
            get
            {
                return this.binaryContentField;
            }
            set
            {
                this.binaryContentField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public bool Signed
        {
            get
            {
                return this.signedField;
            }
            set
            {
                this.signedField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool SignedSpecified
        {
            get
            {
                return this.signedFieldSpecified;
            }
            set
            {
                this.signedFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public bool PersonalData
        {
            get
            {
                return this.personalDataField;
            }
            set
            {
                this.personalDataField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool PersonalDataSpecified
        {
            get
            {
                return this.personalDataFieldSpecified;
            }
            set
            {
                this.personalDataFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public bool Official
        {
            get
            {
                return this.officialField;
            }
            set
            {
                this.officialField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool OfficialSpecified
        {
            get
            {
                return this.officialFieldSpecified;
            }
            set
            {
                this.officialFieldSpecified = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://reg.docu.indexbg.com/", ConfigurationName="DocuServiceReference.DocuServiceSOAP")]
    public interface DocuServiceSOAP
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(DocuServiceReference.DocuServiceFault), Action="", Name="DocuServiceFault")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<DocuServiceReference.GetFileResponse> GetFileAsync(DocuServiceReference.GetFile request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(DocuServiceReference.DocuServiceFault), Action="", Name="DocuServiceFault")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<DocuServiceReference.IdentDocumentResponse> IdentDocumentAsync(DocuServiceReference.IdentDocument request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(DocuServiceReference.DocuServiceFault), Action="", Name="DocuServiceFault")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<DocuServiceReference.GetDocumentResponse> GetDocumentAsync(DocuServiceReference.GetDocument request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(DocuServiceReference.DocuServiceFault), Action="", Name="DocuServiceFault")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<DocuServiceReference.GetDocOfficialByWorkResponse> GetDocOfficialByWorkAsync(DocuServiceReference.GetDocOfficialByWork request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(DocuServiceReference.DocuServiceFault), Action="", Name="DocuServiceFault")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<DocuServiceReference.RegisterDocumentResponse> RegisterDocumentAsync(DocuServiceReference.RegisterDocument request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetFile", WrapperNamespace="http://reg.docu.indexbg.com/", IsWrapped=true)]
    public partial class GetFile
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://reg.docu.indexbg.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int FileID;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://reg.docu.indexbg.com/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string GUID;
        
        public GetFile()
        {
        }
        
        public GetFile(int FileID, string GUID)
        {
            this.FileID = FileID;
            this.GUID = GUID;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetFileResponse", WrapperNamespace="http://reg.docu.indexbg.com/", IsWrapped=true)]
    public partial class GetFileResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://reg.docu.indexbg.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public DocuServiceReference.FileData File;
        
        public GetFileResponse()
        {
        }
        
        public GetFileResponse(DocuServiceReference.FileData File)
        {
            this.File = File;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://reg.docu.indexbg.com/")]
    public partial class DocIdent
    {
        
        private int docIDField;
        
        private bool docIDFieldSpecified;
        
        private string docNumberField;
        
        private int deloSerialField;
        
        private bool deloSerialFieldSpecified;
        
        private System.DateTime docDateField;
        
        private bool docDateFieldSpecified;
        
        private string gUIDField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public int DocID
        {
            get
            {
                return this.docIDField;
            }
            set
            {
                this.docIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool DocIDSpecified
        {
            get
            {
                return this.docIDFieldSpecified;
            }
            set
            {
                this.docIDFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string DocNumber
        {
            get
            {
                return this.docNumberField;
            }
            set
            {
                this.docNumberField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public int DeloSerial
        {
            get
            {
                return this.deloSerialField;
            }
            set
            {
                this.deloSerialField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool DeloSerialSpecified
        {
            get
            {
                return this.deloSerialFieldSpecified;
            }
            set
            {
                this.deloSerialFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public System.DateTime DocDate
        {
            get
            {
                return this.docDateField;
            }
            set
            {
                this.docDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool DocDateSpecified
        {
            get
            {
                return this.docDateFieldSpecified;
            }
            set
            {
                this.docDateFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string GUID
        {
            get
            {
                return this.gUIDField;
            }
            set
            {
                this.gUIDField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="IdentDocument", WrapperNamespace="http://reg.docu.indexbg.com/", IsWrapped=true)]
    public partial class IdentDocument
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://reg.docu.indexbg.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string DocNumber;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://reg.docu.indexbg.com/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int DeloSerial;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://reg.docu.indexbg.com/", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public System.DateTime DocDate;
        
        public IdentDocument()
        {
        }
        
        public IdentDocument(string DocNumber, int DeloSerial, System.DateTime DocDate)
        {
            this.DocNumber = DocNumber;
            this.DeloSerial = DeloSerial;
            this.DocDate = DocDate;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="IdentDocumentResponse", WrapperNamespace="http://reg.docu.indexbg.com/", IsWrapped=true)]
    public partial class IdentDocumentResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://reg.docu.indexbg.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("DocIdent", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public DocuServiceReference.DocIdent[] DocIdent;
        
        public IdentDocumentResponse()
        {
        }
        
        public IdentDocumentResponse(DocuServiceReference.DocIdent[] DocIdent)
        {
            this.DocIdent = DocIdent;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://reg.docu.indexbg.com/")]
    public partial class DocData
    {
        
        private int docIDField;
        
        private bool docIDFieldSpecified;
        
        private string docNumberField;
        
        private int deloSerialField;
        
        private bool deloSerialFieldSpecified;
        
        private System.DateTime docDateField;
        
        private bool docDateFieldSpecified;
        
        private string gUIDField;
        
        private string tehDocNumberField;
        
        private System.DateTime tehDocDateField;
        
        private bool tehDocDateFieldSpecified;
        
        private int docTypeCodeField;
        
        private bool docTypeCodeFieldSpecified;
        
        private string docTypeTextField;
        
        private int docVidCodeField;
        
        private bool docVidCodeFieldSpecified;
        
        private string docVidTextField;
        
        private int registraturaIdField;
        
        private bool registraturaIdFieldSpecified;
        
        private string registraturaTextField;
        
        private string otnosnoField;
        
        private string docInfoField;
        
        private int procDefCodeField;
        
        private bool procDefCodeFieldSpecified;
        
        private string procDefTextField;
        
        private CorrespData correspField;
        
        private ReferentData[] authorField;
        
        private FileData[] fileField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public int DocID
        {
            get
            {
                return this.docIDField;
            }
            set
            {
                this.docIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool DocIDSpecified
        {
            get
            {
                return this.docIDFieldSpecified;
            }
            set
            {
                this.docIDFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string DocNumber
        {
            get
            {
                return this.docNumberField;
            }
            set
            {
                this.docNumberField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public int DeloSerial
        {
            get
            {
                return this.deloSerialField;
            }
            set
            {
                this.deloSerialField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool DeloSerialSpecified
        {
            get
            {
                return this.deloSerialFieldSpecified;
            }
            set
            {
                this.deloSerialFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public System.DateTime DocDate
        {
            get
            {
                return this.docDateField;
            }
            set
            {
                this.docDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool DocDateSpecified
        {
            get
            {
                return this.docDateFieldSpecified;
            }
            set
            {
                this.docDateFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string GUID
        {
            get
            {
                return this.gUIDField;
            }
            set
            {
                this.gUIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string TehDocNumber
        {
            get
            {
                return this.tehDocNumberField;
            }
            set
            {
                this.tehDocNumberField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public System.DateTime TehDocDate
        {
            get
            {
                return this.tehDocDateField;
            }
            set
            {
                this.tehDocDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool TehDocDateSpecified
        {
            get
            {
                return this.tehDocDateFieldSpecified;
            }
            set
            {
                this.tehDocDateFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public int DocTypeCode
        {
            get
            {
                return this.docTypeCodeField;
            }
            set
            {
                this.docTypeCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool DocTypeCodeSpecified
        {
            get
            {
                return this.docTypeCodeFieldSpecified;
            }
            set
            {
                this.docTypeCodeFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=8)]
        public string DocTypeText
        {
            get
            {
                return this.docTypeTextField;
            }
            set
            {
                this.docTypeTextField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=9)]
        public int DocVidCode
        {
            get
            {
                return this.docVidCodeField;
            }
            set
            {
                this.docVidCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool DocVidCodeSpecified
        {
            get
            {
                return this.docVidCodeFieldSpecified;
            }
            set
            {
                this.docVidCodeFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=10)]
        public string DocVidText
        {
            get
            {
                return this.docVidTextField;
            }
            set
            {
                this.docVidTextField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=11)]
        public int RegistraturaId
        {
            get
            {
                return this.registraturaIdField;
            }
            set
            {
                this.registraturaIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool RegistraturaIdSpecified
        {
            get
            {
                return this.registraturaIdFieldSpecified;
            }
            set
            {
                this.registraturaIdFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=12)]
        public string RegistraturaText
        {
            get
            {
                return this.registraturaTextField;
            }
            set
            {
                this.registraturaTextField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=13)]
        public string Otnosno
        {
            get
            {
                return this.otnosnoField;
            }
            set
            {
                this.otnosnoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=14)]
        public string DocInfo
        {
            get
            {
                return this.docInfoField;
            }
            set
            {
                this.docInfoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=15)]
        public int ProcDefCode
        {
            get
            {
                return this.procDefCodeField;
            }
            set
            {
                this.procDefCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ProcDefCodeSpecified
        {
            get
            {
                return this.procDefCodeFieldSpecified;
            }
            set
            {
                this.procDefCodeFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=16)]
        public string ProcDefText
        {
            get
            {
                return this.procDefTextField;
            }
            set
            {
                this.procDefTextField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=17)]
        public CorrespData Corresp
        {
            get
            {
                return this.correspField;
            }
            set
            {
                this.correspField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Author", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=18)]
        public ReferentData[] Author
        {
            get
            {
                return this.authorField;
            }
            set
            {
                this.authorField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("File", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=19)]
        public FileData[] File
        {
            get
            {
                return this.fileField;
            }
            set
            {
                this.fileField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://reg.docu.indexbg.com/")]
    public partial class CorrespData
    {
        
        private int codeField;
        
        private bool codeFieldSpecified;
        
        private string namesField;
        
        private string eIKField;
        
        private string eGNField;
        
        private string lNCField;
        
        private string emailField;
        
        private string phoneField;
        
        private int countryCodeField;
        
        private bool countryCodeFieldSpecified;
        
        private string countryTextField;
        
        private string addressField;
        
        private int addrCountryCodeField;
        
        private bool addrCountryCodeFieldSpecified;
        
        private string addrCountryTextField;
        
        private string postCodeField;
        
        private string ekatteField;
        
        private string locationField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public int Code
        {
            get
            {
                return this.codeField;
            }
            set
            {
                this.codeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool CodeSpecified
        {
            get
            {
                return this.codeFieldSpecified;
            }
            set
            {
                this.codeFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string Names
        {
            get
            {
                return this.namesField;
            }
            set
            {
                this.namesField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string EIK
        {
            get
            {
                return this.eIKField;
            }
            set
            {
                this.eIKField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string EGN
        {
            get
            {
                return this.eGNField;
            }
            set
            {
                this.eGNField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string LNC
        {
            get
            {
                return this.lNCField;
            }
            set
            {
                this.lNCField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string Email
        {
            get
            {
                return this.emailField;
            }
            set
            {
                this.emailField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public string Phone
        {
            get
            {
                return this.phoneField;
            }
            set
            {
                this.phoneField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public int CountryCode
        {
            get
            {
                return this.countryCodeField;
            }
            set
            {
                this.countryCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool CountryCodeSpecified
        {
            get
            {
                return this.countryCodeFieldSpecified;
            }
            set
            {
                this.countryCodeFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=8)]
        public string CountryText
        {
            get
            {
                return this.countryTextField;
            }
            set
            {
                this.countryTextField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=9)]
        public string Address
        {
            get
            {
                return this.addressField;
            }
            set
            {
                this.addressField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=10)]
        public int AddrCountryCode
        {
            get
            {
                return this.addrCountryCodeField;
            }
            set
            {
                this.addrCountryCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool AddrCountryCodeSpecified
        {
            get
            {
                return this.addrCountryCodeFieldSpecified;
            }
            set
            {
                this.addrCountryCodeFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=11)]
        public string AddrCountryText
        {
            get
            {
                return this.addrCountryTextField;
            }
            set
            {
                this.addrCountryTextField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=12)]
        public string PostCode
        {
            get
            {
                return this.postCodeField;
            }
            set
            {
                this.postCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=13)]
        public string Ekatte
        {
            get
            {
                return this.ekatteField;
            }
            set
            {
                this.ekatteField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=14)]
        public string Location
        {
            get
            {
                return this.locationField;
            }
            set
            {
                this.locationField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://reg.docu.indexbg.com/")]
    public partial class ReferentData
    {
        
        private int codeField;
        
        private bool codeFieldSpecified;
        
        private string namesField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public int Code
        {
            get
            {
                return this.codeField;
            }
            set
            {
                this.codeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool CodeSpecified
        {
            get
            {
                return this.codeFieldSpecified;
            }
            set
            {
                this.codeFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string Names
        {
            get
            {
                return this.namesField;
            }
            set
            {
                this.namesField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetDocument", WrapperNamespace="http://reg.docu.indexbg.com/", IsWrapped=true)]
    public partial class GetDocument
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://reg.docu.indexbg.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int DocID;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://reg.docu.indexbg.com/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string GUID;
        
        public GetDocument()
        {
        }
        
        public GetDocument(int DocID, string GUID)
        {
            this.DocID = DocID;
            this.GUID = GUID;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetDocumentResponse", WrapperNamespace="http://reg.docu.indexbg.com/", IsWrapped=true)]
    public partial class GetDocumentResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://reg.docu.indexbg.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public DocuServiceReference.DocData Doc;
        
        public GetDocumentResponse()
        {
        }
        
        public GetDocumentResponse(DocuServiceReference.DocData Doc)
        {
            this.Doc = Doc;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetDocOfficialByWork", WrapperNamespace="http://reg.docu.indexbg.com/", IsWrapped=true)]
    public partial class GetDocOfficialByWork
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://reg.docu.indexbg.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int WorkDocID;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://reg.docu.indexbg.com/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string WorkGUID;
        
        public GetDocOfficialByWork()
        {
        }
        
        public GetDocOfficialByWork(int WorkDocID, string WorkGUID)
        {
            this.WorkDocID = WorkDocID;
            this.WorkGUID = WorkGUID;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetDocOfficialByWorkResponse", WrapperNamespace="http://reg.docu.indexbg.com/", IsWrapped=true)]
    public partial class GetDocOfficialByWorkResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://reg.docu.indexbg.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public DocuServiceReference.DocData OfficialDoc;
        
        public GetDocOfficialByWorkResponse()
        {
        }
        
        public GetDocOfficialByWorkResponse(DocuServiceReference.DocData OfficialDoc)
        {
            this.OfficialDoc = OfficialDoc;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://reg.docu.indexbg.com/")]
    public partial class RegisterDocumentParams
    {
        
        private int registerUserField;
        
        private bool registerUserFieldSpecified;
        
        private string externalCodeField;
        
        private bool createDeloField;
        
        private bool createDeloFieldSpecified;
        
        private string includeDeloNumberField;
        
        private int includeDeloYearField;
        
        private bool includeDeloYearFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public int RegisterUser
        {
            get
            {
                return this.registerUserField;
            }
            set
            {
                this.registerUserField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool RegisterUserSpecified
        {
            get
            {
                return this.registerUserFieldSpecified;
            }
            set
            {
                this.registerUserFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string ExternalCode
        {
            get
            {
                return this.externalCodeField;
            }
            set
            {
                this.externalCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public bool CreateDelo
        {
            get
            {
                return this.createDeloField;
            }
            set
            {
                this.createDeloField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool CreateDeloSpecified
        {
            get
            {
                return this.createDeloFieldSpecified;
            }
            set
            {
                this.createDeloFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string IncludeDeloNumber
        {
            get
            {
                return this.includeDeloNumberField;
            }
            set
            {
                this.includeDeloNumberField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public int IncludeDeloYear
        {
            get
            {
                return this.includeDeloYearField;
            }
            set
            {
                this.includeDeloYearField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool IncludeDeloYearSpecified
        {
            get
            {
                return this.includeDeloYearFieldSpecified;
            }
            set
            {
                this.includeDeloYearFieldSpecified = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="RegisterDocument", WrapperNamespace="http://reg.docu.indexbg.com/", IsWrapped=true)]
    public partial class RegisterDocument
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://reg.docu.indexbg.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public DocuServiceReference.RegisterDocumentParams Params;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://reg.docu.indexbg.com/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public DocuServiceReference.DocData Data;
        
        public RegisterDocument()
        {
        }
        
        public RegisterDocument(DocuServiceReference.RegisterDocumentParams Params, DocuServiceReference.DocData Data)
        {
            this.Params = Params;
            this.Data = Data;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="RegisterDocumentResponse", WrapperNamespace="http://reg.docu.indexbg.com/", IsWrapped=true)]
    public partial class RegisterDocumentResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://reg.docu.indexbg.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public DocuServiceReference.DocData Doc;
        
        public RegisterDocumentResponse()
        {
        }
        
        public RegisterDocumentResponse(DocuServiceReference.DocData Doc)
        {
            this.Doc = Doc;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    public interface DocuServiceSOAPChannel : DocuServiceReference.DocuServiceSOAP, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    public partial class DocuServiceSOAPClient : System.ServiceModel.ClientBase<DocuServiceReference.DocuServiceSOAP>, DocuServiceReference.DocuServiceSOAP
    {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public DocuServiceSOAPClient() : 
                base(DocuServiceSOAPClient.GetDefaultBinding(), DocuServiceSOAPClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.DocuServicePort.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public DocuServiceSOAPClient(EndpointConfiguration endpointConfiguration) : 
                base(DocuServiceSOAPClient.GetBindingForEndpoint(endpointConfiguration), DocuServiceSOAPClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public DocuServiceSOAPClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(DocuServiceSOAPClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public DocuServiceSOAPClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(DocuServiceSOAPClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public DocuServiceSOAPClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<DocuServiceReference.GetFileResponse> DocuServiceReference.DocuServiceSOAP.GetFileAsync(DocuServiceReference.GetFile request)
        {
            return base.Channel.GetFileAsync(request);
        }
        
        public System.Threading.Tasks.Task<DocuServiceReference.GetFileResponse> GetFileAsync(int FileID, string GUID)
        {
            DocuServiceReference.GetFile inValue = new DocuServiceReference.GetFile();
            inValue.FileID = FileID;
            inValue.GUID = GUID;
            return ((DocuServiceReference.DocuServiceSOAP)(this)).GetFileAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<DocuServiceReference.IdentDocumentResponse> DocuServiceReference.DocuServiceSOAP.IdentDocumentAsync(DocuServiceReference.IdentDocument request)
        {
            return base.Channel.IdentDocumentAsync(request);
        }
        
        public System.Threading.Tasks.Task<DocuServiceReference.IdentDocumentResponse> IdentDocumentAsync(string DocNumber, int DeloSerial, System.DateTime DocDate)
        {
            DocuServiceReference.IdentDocument inValue = new DocuServiceReference.IdentDocument();
            inValue.DocNumber = DocNumber;
            inValue.DeloSerial = DeloSerial;
            inValue.DocDate = DocDate;
            return ((DocuServiceReference.DocuServiceSOAP)(this)).IdentDocumentAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<DocuServiceReference.GetDocumentResponse> DocuServiceReference.DocuServiceSOAP.GetDocumentAsync(DocuServiceReference.GetDocument request)
        {
            return base.Channel.GetDocumentAsync(request);
        }
        
        public System.Threading.Tasks.Task<DocuServiceReference.GetDocumentResponse> GetDocumentAsync(int DocID, string GUID)
        {
            DocuServiceReference.GetDocument inValue = new DocuServiceReference.GetDocument();
            inValue.DocID = DocID;
            inValue.GUID = GUID;
            return ((DocuServiceReference.DocuServiceSOAP)(this)).GetDocumentAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<DocuServiceReference.GetDocOfficialByWorkResponse> DocuServiceReference.DocuServiceSOAP.GetDocOfficialByWorkAsync(DocuServiceReference.GetDocOfficialByWork request)
        {
            return base.Channel.GetDocOfficialByWorkAsync(request);
        }
        
        public System.Threading.Tasks.Task<DocuServiceReference.GetDocOfficialByWorkResponse> GetDocOfficialByWorkAsync(int WorkDocID, string WorkGUID)
        {
            DocuServiceReference.GetDocOfficialByWork inValue = new DocuServiceReference.GetDocOfficialByWork();
            inValue.WorkDocID = WorkDocID;
            inValue.WorkGUID = WorkGUID;
            return ((DocuServiceReference.DocuServiceSOAP)(this)).GetDocOfficialByWorkAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<DocuServiceReference.RegisterDocumentResponse> DocuServiceReference.DocuServiceSOAP.RegisterDocumentAsync(DocuServiceReference.RegisterDocument request)
        {
            return base.Channel.RegisterDocumentAsync(request);
        }
        
        public System.Threading.Tasks.Task<DocuServiceReference.RegisterDocumentResponse> RegisterDocumentAsync(DocuServiceReference.RegisterDocumentParams Params, DocuServiceReference.DocData Data)
        {
            DocuServiceReference.RegisterDocument inValue = new DocuServiceReference.RegisterDocument();
            inValue.Params = Params;
            inValue.Data = Data;
            return ((DocuServiceReference.DocuServiceSOAP)(this)).RegisterDocumentAsync(inValue);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.DocuServicePort))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                result.Security.Mode = System.ServiceModel.BasicHttpSecurityMode.Transport;
                return result;
            }
            else if (endpointConfiguration == EndpointConfiguration.DocuServicePortHTTP) 
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                result.Security.Mode = System.ServiceModel.BasicHttpSecurityMode.None;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.DocuServicePort))
            {
                return new System.ServiceModel.EndpointAddress("https://test.indexbg.bg/DocuWork/DocuService");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return DocuServiceSOAPClient.GetBindingForEndpoint(EndpointConfiguration.DocuServicePort);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return DocuServiceSOAPClient.GetEndpointAddress(EndpointConfiguration.DocuServicePort);
        }
        
        public enum EndpointConfiguration
        {
            
            DocuServicePort,
            DocuServicePortHTTP,
        }
    }
}
